### ISSUE TITLE
Fixes to SKOS modeling

### ISSUE THREAD

**Issue by VladimirAlexiev** [julianrojas87/era-vocabulary#36]
1) These are wrong 
```
era-op-types:OperationalPointType
skos:inScheme era-skos:  .
era-skos: a skos:ConceptScheme
```
because a ConceptScheme is a single thesaurus and consists of Concepts, not of subclasses of Concept .

It's better to declare 
```
era-op-types:OperationalPointType
rdfa:isDefinedBy era-skos:  .
era-skos: a owl:Ontology
```
2) each Concept must belong to a ConceptScheme. So in addition to this
```
era-op-types:borderPoint a era-op-types:OperationalPointType
```
You better add this
```
era-op-types:borderPoint skos:inScheme era-op-types:OperationalPointType.
era-op-types:OperationalPointType a skos:ConceptScheme.
```
I don't think it's a bug problem that `era-op-types:OperationalPointType` wull become both an individual ( `skos:ConceptScheme`) and a Class. OWL Punning allows that.

**Comment by julianrojas87** [comment]
Thanks for pointing out this issue @VladimirAlexiev. The way the referenced data vocabulary is defined now, was just an initial prototype which will change now that we are moving into a production stage. The idea would be to drop the [hybrid OWL/SKOS pattern](https://www.w3.org/2006/07/SWD/SKOS/skos-and-owl/master.html#Hybrids) and just publish independent `skos:ConceptScheme`s for each taxonomy. This makes sense from a management point of view, given that most likely different authorities should be in charge to define these concepts.

I personally like the hybrid OWL/SKOS approach and with the solution you propose we can actually have independent `skos:ConceptScheme`s for each taxonomy. However the approach would not be supported anymore because it requires some reasoning capabilities from the SKOS management tools that will be used,  to handle this:
 ```turtle
 era-op-types:OperationalPointType rdfs:subClassOf skos:Concept .
 era-op-types:borderPoint a era-op-types:OperationalPointType
 ```

**Comment by VladimirAlexiev** [comment]
Yes, thesaurus management systems like VocBench, PoolParty and Synaptica Graphite manage multiple ConceptSchemes but not multiple classes. (Btw my ENDORSE presentation starts with them https://github.com/VladimirAlexiev/ontotext-graphdb-applications/raw/master/Diverse%20Uses%20of%20a%20Semantic%20Graph%20Database%20for%20Knowledge%20Organization%20and%20Research%20(ENDORSE%202021).pptx)

But you can add extra triples with GDB custom rules or SPARQL insert.
